---
# This assigns a PR to its author
addAssignees: author

reviewers:
  # The default reviewers
  defaults:
    - maintainers

  groups:
    maintainers:
      - carlisia
      - zubron
      - ardan-bkennedy
      - ashish-amarnath

    tech-writer:
      - ardan-bkennedy

files:
  'public/**':
    - tech-writer
  '**/*.md':
    - tech-writer

options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: true

# Randomly pick reviewers up to this number.
# Do not set this option if you'd like to assign all matching reviewers.
number_of_reviewers: 2
