reviewers:
  # The default reviewers
  defaults:
    - maintainers

  groups:
    maintainers:
      - nrb
      - ashish-amarnath
      - carlisia
      - zubron
      - dsu-igeek
      - jenting

    tech-writer:
      - a-mccarthy 

files:
  'site/**':
    - tech-writer
  '/design/**':
    - maintainers

options:
  ignore_draft: true
  ignored_keywords:
    - WIP 
  enable_group_assignment: true

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 2

addAssignees: author