baseURL = "https://grokkingtech.io/"
languageCode = "en-us"
title = "grokkingtech.io"
copyright = "Carlisia Campos"
theme = "ghostwriter2"

[Author]
    name = "Carlisia Campos"
    profile = "https://twitter.com/carlisia"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Carlisia's blog"
    description = "Blogging mostly about cloud native technologies and concepts"
    github = "https://github.com/carlisia"
    linkedin = "https://linkedin.com/in/carlisia/"
    twitter = "https://twitter.com/carlisia"
    stackoverflow = "https://stackoverflow.com/users/3389881/carlisia"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
